#!/bin/bash

output=$(top -l 1 | grep -o '^CPU usage: [0-9]\{1,3\}\.[0-9]\{1,2\}% user')
output="${output#CPU usage: }"
cpu_load="${output%\% user}"

output=$(top -l 1 | grep -o '^PhysMem: [0-9]\+[a-zA-Z] used')
output="${output#PhysMem: }"
memory_used="${output% used}"

printf '󰊚 %6.2f%% %s' $cpu_load "$memory_used"

