#!/bin/bash

current_command=${1#-}
current_path=$2
window_name=$3
option=$4
icon=$5

print-icon()
{
	case "$1" in
		cmake|ccmake|make|ninja) printf ' ' ;; # 󱁤
		dev|development) printf '󱁤 ' ;;
		gcc|cpp) printf '󰙲 ' ;;
		gdb|dbg|debug) printf ' ' ;; # 󱁤 
		ghc*) printf ' ' ;;
		git|lazygit) printf '󰊢 ' ;; # 󰊢  
		htop|top) printf '󰑮 ' ;; #  󰑮
		lua|luarocks) printf '󰢱 ' ;;
		nano|pico) printf '󱇨 ' ;;
		nc|ncat|netcat|ping|network) printf '󰲝 ' ;; # 󰲝 󱘖
		nvim) printf ' ' ;; #  
		python|Python) printf ' ' ;;
		ranger|mc|nnn|vifm|yazi|files) printf '󰉓 ' ;;
		ruby) printf '󰴭 ' ;;
		sql|sqlite|sqlite3|database) printf '󰆼 ' ;;
		test|tests) printf '󰢨 ' ;; # 󰢨 󰄹 󰤑 
		vim) printf ' ' ;; #  

		help|man|?) printf '󰘥 ' ;; # 󰋖
		flask) printf ' ' ;;
		game) printf '󰊴 ' ;; #  󱢡 󰊴 
		*) printf '󰘔 ' ;;
	esac
}

component-count-greater-than()
{
	local path=$1
	local count=$2

	local component_count=0
	local index
	for (( index = 0; index < ${#path}; ++index ))
	do
		local character="${path:$index:1}"
		if [[ $character != '/' ]]
		then
			continue
		fi

		(( ++component_count ))
		if (( component_count > count))
		then
			return 0
		fi
	done

	return 1
}

shorten-path()
{
	local path=$1

	if (( ${#path} <= 24 ))
	then
		printf '%s' "$path"
		return
	fi

	if component-count-greater-than "$path" 2
	then
		path="${path:1}"
		printf '/%s/.../%s' "${path%%/*}" "${path##*/}"
	else
		printf '/.../%s' "${path##*/}"
	fi
}

if [ -n "$window_name" ]
then
	if [[ $option != '-i' ]]
	then
		print-icon "$window_name"
	elif [ -n "$icon" ]
	then
		print-icon "$icon"
	fi

	printf '%s' "$window_name"
	exit
fi

current_shell=${SHELL##*/}
if [[ $current_command != $current_shell ]]
then
	print-icon "$current_command"
	printf '%s' "$current_command"
	exit
fi

relative_path="${current_path#$HOME}"
if [[ $relative_path == $current_path ]]
then
	current_path=$(shorten-path "$current_path")
	printf '󰆍 %s/' "$current_path"
else
	relative_path=$(shorten-path "$relative_path")
	printf '󰆍 ~%s/' "$relative_path"
fi

