#!/bin/bash

BORDER_FG=$(\tmux display-message -p '#{@CS_MENU_BORDER_FG}')
SELECTED_FG=$(\tmux display-message -p '#{@CS_MENU_SELECTED_FG}')
SELECTED_BG=$(\tmux display-message -p '#{@CS_MENU_SELECTED_BG}')

attached_session=$(\tmux display-message -p '#S')
sessions=($(\tmux list-sessions -F '#S'))

menu_items=()
index=1
selected=0
for session in "${sessions[@]}"
do
	if [[ $session == $attached_session ]]
	then
		item="#{@ICON_CURRENT_SESSION}$session"
		selected=$(( index - 1 ))
	else
		item="  $session"
	fi

	menu_items+=("$item" $index "switch-client -t $session")
	(( ++index ))
done

\tmux set-option -g status-left "\
 #[fg=#{@CS_STATUS_SELECTED_FG},bg=#{@CS_STATUS_SELECTED_BG},bold]\
 #{@ICON_SESSION} #S \
#[fg=#{@CS_STATUS_FG},bg=#{@CS_STATUS_BG}] #{@ICON_DELIMITER} "

\tmux set-option -w -g window-status-current-format "\
#[fg=#{@CS_STATUS_SELECTED_INACTIVE_FG},bg=#{@CS_STATUS_SELECTED_INACTIVE_BG},bold]\
 #(~/.config/tmux/auto-window-name #{pane_current_command} #{pane_current_path} #{window_name}) \
#[fg=default,bg=defult]"

\tmux display-menu \
	-T " #{@ICON_SWITCH_SESSION} Switch session " \
	-x 1 \
	-y S \
	-b heavy \
	-S "fg=$BORDER_FG" \
	-H "fg=$SELECTED_FG,bg=$SELECTED_BG" \
	-C $selected "${menu_items[@]}"

\tmux set-option -g status-left "  #{@ICON_SESSION} #S  #{@ICON_DELIMITER} "

\tmux set-option -w -g window-status-current-format "\
#[fg=#{@CS_STATUS_SELECTED_FG},bg=#{@CS_STATUS_SELECTED_BG},bold]\
 #(~/.config/tmux/auto-window-name #{pane_current_command} #{pane_current_path} #{window_name}) \
#[fg=default,bg=defult]"

