#!/bin/bash

target_pane=$1

current_pane=$(\tmux display-message -p '#{pane_index}')
if [[ $current_pane != $target_pane ]]
then
	\tmux select-pane -t $target_pane
else
	zoomed=$(\tmux display-message -p '#{window_zoomed_flag}')
	if [[ $zoomed == 0 ]]
	then
		\tmux resize-pane -Z
	fi
fi

