#!/bin/bash

current_command=${1#-}
current_path=$2
window_name=$3
option=$4
icon=$5

current_shell=${SHELL##*/}

print-icon()
{
	case "$1" in
		cmake|ccmake|make|ninja) printf ' ' ;; # 󱁤
		dev|development) printf '󱁤 ' ;;
		gcc|cpp) printf '󰙲 ' ;;
		gdb) printf ' ' ;; # 󱁤 
		ghc*) printf ' ' ;;
		git|lazygit) printf '󰊢 ' ;; # 󰊢  
		htop|top) printf '󰑮 ' ;; #  󰑮
		lua|luarocks) printf '󰢱 ' ;;
		nano|pico) printf '󱇨 ' ;;
		nc|ncat|netcat|ping|network) printf '󰲝 ' ;; # 󰲝 󱘖
		nvim) printf ' ' ;; #  
		python|Python) printf ' ' ;;
		ranger|mc|nnn|vifm|yazi|files) printf '󰉓 ' ;;
		ruby) printf '󰴭 ' ;;
		sql|sqlite|sqlite3|database) printf '󰆼 ' ;;
		test|tests) printf '󰢨 ' ;; # 󰢨 󰄹 󰤑 
		vim) printf ' ' ;; #  

		help|man|?) printf '󰘥 ' ;; # 󰋖
		flask) printf ' ' ;;
		game) printf '󰊴 ' ;; #  󱢡 󰊴 
		*) printf '󰘔 ' ;;
	esac
}

if [ -n "$window_name" ]
then
	if [[ $option != '-i' ]]
	then
		print-icon "$window_name"
	elif [ -n "$icon" ]
	then
		print-icon "$icon"
	fi

	printf '%s' "$window_name"
	exit
fi

if [[ $current_command != $current_shell ]]
then
	print-icon "$current_command"
	printf '%s' "$current_command"
	exit
fi

relative_path="${current_path#$HOME}"
if [[ $relative_path == $current_path ]]
then
	printf '󰆍 %s' "$current_path"
	exit
fi

printf '󰆍 ~%s/' "$relative_path"

