#!/bin/bash

source ~/.config/tmux/scripts/private/popup

widgets=$1
widget_index=$2

OLD_IFS="$IFS"
IFS=$'\n'
lines=($(~/.config/tmux/scripts/private/battery-info))
IFS="$OLD_IFS"

window_width=$(\tmux display-message -p '#{window_width}')
widget_delimiter=$(\tmux display-message -p '#{@ICON_DELIMITER}')
popup-configuration $window_width "$widgets" $widget_index "$widget_delimiter" 1 "${lines[@]}"
content=$(popup-pad-content 1 "${lines[@]}")

popup-display-info " #{@ICON_BATTERY} Battery " $POPUP_CONFIGURATION_RETURN__WIDTH $POPUP_CONFIGURATION_RETURN__HEIGHT $POPUP_CONFIGURATION_RETURN__X "$content"

