#!/usr/bin/env bash

source ~/.config/tmux/scripts/private/popup

widgets=$1
widget_index=$2

OLD_IFS="$IFS"
IFS=$'\n'
lines=($(cal -h))
IFS="$OLD_IFS"

content=$(~/.config/tmux/scripts/private/calendar $(date -v-1m '+%Y-%m') "${lines[@]}")
window_width=$(\tmux display-message -p '#{window_width}')
widget_delimiter=$(\tmux display-message -p '#{@ICON_DELIMITER}')
popup-configuration $window_width "$widgets" $widget_index "$widget_delimiter" 0 "${lines[@]}"

popup-display-static "󰃭 Calendar" $POPUP_CONFIGURATION_RETURN__WIDTH $POPUP_CONFIGURATION_RETURN__HEIGHT $POPUP_CONFIGURATION_RETURN__X "$content"

