#!/usr/bin/env bash

source ~/.config/tmux/scripts/private/popup-utils
source ~/.config/tmux/scripts/private/network-utils

network-info
title="$NETWORK_INFO_RETURN__TITLE"
content="$NETWORK_INFO_RETURN__CONTENT"

widgets=$1
widget_index=$2

BORDER_FG=$(\tmux display-message -p '#{@CS_MENU_BORDER_FG}')
window_width=$(\tmux display-message -p '#{window_width}')

OLD_IFS="$IFS"
IFS=$'\n'
lines=($(printf ' %s ' "$content"))
IFS="$OLD_IFS"

widget_delimiter=$(\tmux display-message -p '#{@ICON_DELIMITER}')
popup-width "${lines[@]}"; width=$?
popup-height "${lines[@]}"; height=$?
x=$(popup-x $width $window_width "$widget_delimiter" $widget_index "$widgets")

\tmux display-popup \
	-T " $title "\
	-b heavy \
	-S "fg=$BORDER_FG" \
	-w $width \
	-h $height \
	-x $x \
	-y S \
	"tput civis && printf \"$content\""

