#!/usr/bin/env bash

source ~/.config/tmux/scripts/private/popup

widgets=$1
widget_index=$2

OLD_IFS="$IFS"
IFS=$'\n'
lines_colored=($(~/.config/tmux/scripts/private/world-clock ~/.config/tmux/world-clocks))
lines=($(~/.config/tmux/scripts/private/world-clock ~/.config/tmux/world-clocks --no-color))
IFS="$OLD_IFS"

window_width=$(\tmux display-message -p '#{window_width}')
widget_delimiter=$(\tmux display-message -p '#{@ICON_DELIMITER}')
popup-configuration $window_width "$widgets" $widget_index "$widget_delimiter" 1 "${lines[@]}"
content=$(popup-pad-content 1 "${lines_colored[@]}")

popup-display-static " World Clock" $POPUP_CONFIGURATION_RETURN__WIDTH $POPUP_CONFIGURATION_RETURN__HEIGHT $POPUP_CONFIGURATION_RETURN__X "$content"

