#!/bin/bash

pane_width=$1
pane_height=$2
current_path=$3
cmd="${@:4}"

if (( $pane_width / 2 >= $pane_height ))
then
	\tmux split-window -h -c "$current_path" ${cmd[@]}
else
	\tmux split-window -v -c "$current_path" ${cmd[@]}
fi

